### ISSUE TITLE
Broken No launch.toml process type

### ISSUE THREAD

**Issue by brandonkal** [heroku/nodejs-npm-buildpack#10]
Node builds do not function, and it appears to be as a result of no defined processes in launch.toml (which is not added here).

## Given:
```sh
git clone https://github.com/heroku/node-js-getting-started.git
cd node-js-getting-started
pack build --builder heroku/buildpacks:18 js-heroku
docker run --rm -p 8080:8080 js-heroku

```
## Result
Error: failed to launch: determine start command: process type web was not found
The docker file built is present on dockerhub at `brandonkal/js-heroku`

As discussed on Slack, this works: `docker run -p 8080:8080 js-heroku "npm start"`

**Comment by danielleadams** [comment]
@brandonkal This is fixed with https://github.com/heroku/nodejs-npm-buildpack/pull/11, so I'm going to close this as it is resolved.
