### ISSUE TITLE
Yarn support

### ISSUE THREAD

**Issue by brandonkal** [heroku/nodejs-npm-buildpack#13]
The nodejs-engine-buildpack installs yarn if a `yarn.lock` file is present. This buildpack should run yarn instead of npm if yarn is available. This will ensure the lock file is respected.

**Comment by danielleadams** [comment]
Hi @brandonkal, thanks for the issue. We're going to add yarn support in a different buildpack for a different builder path. I'll keep this issue open until it's posted so that it's communicated

**Comment by brandonkal** [comment]
Thank you. That makes sense given the name of this repo. I am curious how that would work as I am still exploring the CNB concept. Would that not require logic in this buildpack so they both don't run? It appears that the detect methods to apply both would be about the same.

**Comment by hone** [comment]
@brandonkal the yarn buildpack would detect for a `yarn.lock` vs this one. We can have just two buildpack groups one for `yarn` and one for `npm`.

**Comment by danielleadams** [comment]
@brandonkal Here's the yarn buildpack: https://github.com/heroku/nodejs-yarn-buildpack.

**Comment by danielleadams** [comment]
I'm going to close this issue since there's functionality supporting yarn now.
