### ISSUE TITLE
heroku doesn't execute my code exactly as my terminal/node would.

### ISSUE THREAD

**Issue by Jytesh** [heroku/nodejs-npm-buildpack#20]
ill try to explain, first as soon as the message is received a skin js object is built and sent to this functionretrieveskin), an embed(think a loading animation) is sent and that message is stored.Then canvas makes an image for me(which takes some time mind it) using the skin object(different image for each command) so once that image is build, the loading embed is deleted and the new one is sent, if the image fails to build the Error Time Out function(after 10 seconds) is called, and the loading embed becomes an error embed
https://hastebin.com/pimovaxila.js - The embed gets deleted after my image is sent, if i use node in my terminal, but it won't get deleted if i use heroku(sometimes)

**Comment by danielleadams** [comment]
Hi @Jytesh - is this for something you are running on Heroku, or are you testing with cloud native buildpacks? If this is something on Heroku - you'll want to open an Issue here: https://github.com/heroku/heroku-buildpack-nodejs, or I would advise opening a support ticket here: https://help.heroku.com/.

**Comment by Jytesh** [comment]
Its something I am running on heroku with nodejs buildpack

**Comment by danielleadams** [comment]
Okay, this is the wrong buildpack then. Heroku uses this buildpack: https://github.com/heroku/heroku-buildpack-nodejs. If you open an issue there, I can address it and close this one.

**Comment by Jytesh** [comment]
> Okay, this is the wrong buildpack then. Heroku uses this buildpack: https://github.com/heroku/heroku-buildpack-nodejs. If you open an issue there, I can address it and close this one.

https://github.com/heroku/heroku-buildpack-nodejs/issues/738#issue-557294708,Done

**Comment by danielleadams** [comment]
@Jytesh thanks. I'll take a look.
