### ISSUE TITLE
use_npm_ci() function returns true when my node version is 5.6.0

### ISSUE THREAD

**Issue by kissmikijr** [heroku/nodejs-npm-buildpack#22]
So I found that the use_npm_ci() function returns true if my npm version is exactly 5.6.0. For this reason the build is trying to use npm ci command. Unfortunately npm 5.6.0 does not have ci command so the build fails.

Correct behaviour should be that when my npm is 5.6.0 it should return false to use the npm install command in the build function.

**Comment by kissmikijr** [comment]
https://github.com/heroku/nodejs-npm-buildpack/blob/master/lib/build.sh#L28

this line should be: [[ "$major" -gt "5" || ("$major" == "5" && "$minor" -gt "6") ]]

**Comment by danielleadams** [comment]
Thanks for reporting this 👍

**Comment by danielleadams** [comment]
Fixed in 0.1.4 - thanks for the patch @kissmikijr!
